version: "3.1"

services:
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
  my-app:
    env_file:
      - ./config/prod.env
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "5000"
